TK_F09/urls.py
from os import stat
from django.contrib import admin
from django.urls import include, path
import form_postingan.urls as form_postingan
from django.urls.conf import include

import form_vaksin.urls as form_vaksin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('form-postingan/', include(form_postingan)),
    path('form/', include(form_vaksin)),
    path('apis/v1/', include('apis.urls')),
    path('data', include('data.urls'))
]

apis/urls.py
from django.urls import path
from .views import ListFormPostingan, DetailFormPostingan

urlpatterns = [

    path('', ListFormPostingan.as_view()),
    path('<int:pk>/', DetailFormPostingan.as_view())
]

data/urls.py
from django.urls import path
from .views import ListFormVaksin, DetailFormVaksin

urlpatterns = [

    path('', ListFormVaksin.as_view()),
    path('<int:pk>/', DetailFormVaksin.as_view())
]

form_postingan/urls.py
from django.urls import path
from .views import add_post, index
from django.conf.urls import url
from django.conf.urls import include

urlpatterns = [
    path('', add_post, name='add_note'),
    path('hasil/', index, name='index'),
]

form_vaksin/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('add', add_vaksin, name='add_vaksin'),
    path('json', json, name= 'json'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('tempSearch/', views.tempSearch, name='tempSearch'),
    path('result', views.result, name='result'),
    path('sertifikat_vaksin/', views.sertifikat_vaksin, name='sertifikat_vaksin'),
    path('information/', views.informasi, name='informasi'),
    path('newspage/', views.newspage, name='newspage'),
    path('json', views.json, name='json'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('time_json', views.json, name='time_json'),
    path('dataPostingan', views.jsonPostingan, name='jsonPostingan'),
    path('jsonModels', views.jsonModels, name='jsonModels')
]

apis/models.py
from django.db import models

# Create your models here.

data/models.py
from django.db import models

# Create your models here.

form_postingan/models.py
from django.db import models

# Create your models here.
class Postingan(models.Model):
    title = models.CharField(max_length=30)
    body = models.TextField()

form_vaksin/models.py
from django.db import models


class Vaksin(models.Model):
    name = models.CharField(max_length=30)
    # TODO Implement missing attributes in Friend model
    dob = models.DateField()
    nik = models.CharField(max_length=30)
    jumlahvaksin = models.CharField(max_length=30)
    tanggalvaksin = models.DateField()
    lokasivaksin = models.CharField(max_length=30)

main/models.py
from django.db import models

# Create your models here.
class tempPost(models.Model):
    Title = models.TextField()
    SubTitle = models.TextField(null=True, blank=True)
    Post = models.TextField()
    File = models.TextField(null=True, blank=True)

form_postingan/forms.py
from django import forms
from django.forms import fields
from main.models import tempPost

class PostinganForm(forms.ModelForm):
    class Meta:
        model = tempPost
        fields='__all__'
        labels = {
            'Title': 'title',
            'SubTitle': 'subTitle',
            'Post': 'body',
            'File': 'file'
        }

form_vaksin/forms.py
from django import forms
from .models import Vaksin

class VaksinForm(forms.ModelForm):
	class Meta:
		model = Vaksin
		fields = "__all__"
	error_messages = {
		'required' : 'Please Type'
	}
	

apis/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

# Create your views here.
from main import models
from .serializers import PostinganSerializer
from rest_framework import generics

class ListFormPostingan(generics.ListCreateAPIView):
    queryset = models.tempPost.objects.all()
    serializer_class = PostinganSerializer

class DetailFormPostingan(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.tempPost.objects.all()
    serializer_class = PostinganSerializer

data/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

# Create your views here.
from main import models
from .serializers import VaksinSerializer
from rest_framework import generics

class ListFormVaksin(generics.ListCreateAPIView):
    queryset = models.tempPost.objects.all()
    serializer_class = VaksinSerializer

class DetailFormVaksin(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.tempPost.objects.all()
    serializer_class = VaksinSerializer

form_postingan/views.py
from django.db import connections
from django.shortcuts import render, redirect
from .forms import PostinganForm
from main.models import tempPost
from .models import Postingan
from django.http import JsonResponse
from django.core import serializers
from django.http import HttpResponse
import json

# Create your views here.
def index(request):
    post = tempPost.objects.all().values()
    response = {'posts': post}
    return render(request, 'index.html', response)

def add_post(request):
    if request.method == "POST":
        form = PostinganForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('hasil/')
    else:
        form = PostinganForm()
    
    html = 'form_postingan.html'
    return render(request, html, {'form':form})

form_vaksin/views.py
from django.shortcuts import render
from .models import Vaksin
from .forms import VaksinForm
from django.http.response import HttpResponse, HttpResponseRedirect
from django.core import serializers

# Create your views here.

def index(request):
    vaksin = Vaksin.objects.all().values()  # TODO Implement this
    response = {'vaksin': vaksin}
    return render(request, 'vaksin_index.html', response)

def add_vaksin(request):
    form = VaksinForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/')
    return render(request, "vaksin_form.html", {'form':form})

def json(request):
    data = serializers.serialize('json', Vaksin.objects.all())
    return HttpResponse(data, content_type="application/json")
    

main/views.py
from django.http import request
from django.shortcuts import render
from django.db.models import Q
from .models import tempPost
from form_vaksin.models import Vaksin
import requests
from time import localtime, strftime
from django.http import JsonResponse
import datetime
from django.core import serializers
from django.http.response import HttpResponse
from django.forms.models import model_to_dict
from django.views.decorators.csrf import csrf_exempt

def home(request):
    response = requests.get('https://api.kawalcorona.com/indonesia').json()
    data = tempPost.objects.all()
    return render(request, 'main/beranda.html', {'response':response, 'data':data})

def tempSearch(request):
    return render(request, 'main/tempSearch.html',{})

def result(request):
    if request.method == 'GET':
        search = request.GET.get('search')
        post = tempPost.objects.filter(Q(Title__icontains=search))
        return render(request, 'main/result.html',{'results':post , 'search':search})

def sertifikat_vaksin(request):
    data = Vaksin.objects.all()
    response = {'data' : data}
    return render(request, 'main/sertifikat_vaksin.html', response)

def informasi(request):
    newspage = tempPost.objects.all()
    response = {'newspage': newspage}
    return render(request, 'main/informasi.html', response)

def newspage(request):
    newspage = tempPost.objects.all()
    response = {'newspage': newspage}
    return render(request, 'main/newspage.html', response)
    

def json(request):
    t = localtime()
    ret = strftime("%H:%M:%S", t)
    return JsonResponse(ret, safe=False)

def login(request):
    return render(request, 'main/login.html')

def register(request):
    return render(request, 'main/register.html')

def jsonPostingan(request):
    data = serializers.serialize('json', tempPost.objects.all())
    return HttpResponse(data, content_type="application/json")

@csrf_exempt
def jsonModels(request):
    if request.method == 'GET':
 
        search = request.GET.get('search')
        post = tempPost.objects.filter(Q(Title__icontains=search))

        O = {}
        i = 0
            
        for one in post:
            O[i] = model_to_dict(one)
            i += 1
            
          
        return JsonResponse(O, safe=False)

form_postingan/templates/form_postingan.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="//cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap');
        body {
            background-image:url(https://media.discordapp.net/attachments/906082615877042181/906125074988421150/Untitled_Artwork.png?width=759&height=530);
            background-repeat: no-repeat;
            background-size: cover;
            font-family: "Rubik", sans-serif;
        }
        #judul {
            text-align: center;
            font-family: "Rubik", sans-serif;
            font-size: auto;
        }
        .container {
            background: #dfeff8;
            padding: 30px;
            margin: 50px auto;
            box-shadow: 1px 1px 25px rgba(0, 0, 0, 0.35);
            border-radius: 30px;
            border: 6px solid #305A72;
        }
        .card {
            border-radius: 30px;
            
        }
        .label {
            font-family: Georgia;
        }
        .button {
            border: none;
            color: white;
            padding: 12px 24px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 12px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
            border-radius: 20px;
        }
        .bsubmit {
            background-color: rgb(90, 233, 90); 
            color: white; 
        }
        .breset {
            background-color: rgb(250, 213, 1); 
            color: white; 
        }
        .bsubmit:hover {
            background-color: rgb(31, 163, 31);
            color: rgb(255, 255, 255);
        }
        .breset:hover {
            background-color: rgb(216, 202, 7);
            color: rgb(255, 255, 255);
        }

    </style>

    <title>Form Postingan Informasi COVID-19</title>
    
  </head>
  <body>
    {% include "main/header.html" %}
    <div class="container">
        <div class="card mt-3 mb-3 border-dark">
            <div class="card-header border-dark">
                
                <h2 id="judul">Form Postingan Informasi COVID-19</h2>
            </div>
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data" id="formpost">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" name="title" class="form-control" id="title" placeholder="Masukkan Judul Postingan">
                    </div>
                    <div class="form-group">
                        <label>Sub Title</label>
                        <input type="text" name="subTitle" class="form-control" id="subTitle" placeholder="Masukkan Sub Judul Postingan">
                    </div>
                    <div class="form-group">
                        <label>Content</label>
                        <textarea class="form-control" name="body" id="body" rows="15"></textarea>
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="customFile">Upload URL Image</label>
                        <textarea class="form-control" name="image" id="image" rows="2"></textarea>
                    </div>
                </form>
            </div>
            <div class="card-footer border-dark">
                <button class="button breset" onclick="hapus()" id="resetBtn">Reset</button>
                <button class="button bsubmit float-right" onclick="submit()" id="submitBtn">Submit</button>
            </div>
        </div>
    </div>

    {% include "main/footer.html" %}
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
        function submit() {
            console.log("dipencet");
            var post_url = $(this).attr("action");
            var request_method = $(this).attr("method"); 
	        var form_data = $(this).serialize();

            $.ajax({
                url : "",
                type: "POST",
                data : { Title : $('#title').val(), SubTitle : $('#subTitle').val(), Post : $('#body').val(), File : $('#image').val(),'csrfmiddlewaretoken':"{{ csrf_token }}" },

                // handle a successful response
                success : function(json) {
                    alert("Postingan berhasil disubmit!")
                    window.location.assign('/information')
                    console.log(json); // log the returned json to the console
                    console.log("success"); // another sanity check
                },

                // handle a non-successful response
                error : function(xhr,errmsg,err) {
                    alert("Postingan gagal disubmit")
                    console.log("error"); 
                }
            })
        }

        function hapus(){
            $("#title").val("");
            $("#subTitle").val("");
            $("#body").val("");
            $("#image").val("");
        }

    </script>
  </body>
</html>

form_postingan/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
        body {
            background-color: rgb(255, 246, 230);
        }
        table {
            width: 60%;
        }
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
            border-spacing: 10px;
            margin-left: auto;
            margin-right: auto;
        }
        th, td {
            font-family: "Lucida Sans", monospace;
            padding: 10px;
        }
        th {
            text-align: left;
            background-color: rgb(247, 172, 164);
        }
        tr:nth-child(even){background-color: #fff4f4}
        h1 {
            text-align: center;
            font-family: "Trebuchet MS", sans-serif;
        }
        .topnav {
            overflow: hidden;
            background-color: maroon;
            font-family: avenir;
        }

        .topnav a {
            float:left;
            color: whitesmoke;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }  

        .topnav a:hover {
            background-color: rgb(241, 200, 200);
            color: maroon;
        }

        .topnav a.active {
            background-color: rgb(201, 100, 125);
            color: white;
        }
      </style>
    <meta charset="UTF-8" />
    <title>Note</title>
  </head>
  <body>

    <h1>Postingan</h1>
    <table>
      <tr>
        <th>Title</th>
        <th>Sub Title</th>
        <th>Body</th>
        <th>URL image</th>
      </tr>
      {% for post in posts %}
      <tr>
        <td>{{post.Title}}</td>
        <td>{{post.SubTitle}}</td>
        <td>{{post.Post}}</td>
        <td>{{post.File}}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

form_vaksin/templates/vaksin_form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'vaksin_style.css' %}" />
  <title>Document</title>
{% endblock meta %}
{% block content %}
{% include "main/header.html" %}
  <form action="" method="POST">
    {% csrf_token %}
    <h1>Pendaftaran Vaksin</h1>
    <fieldset>
      <!-- <legend><span class="number"></span>Form Vaksinasi</legend> -->
      <label for="name">Nama:</label>
      {{form.name}}
      <label for="dob">Tanggal Lahir:</label>
      {{form.dob}}
      <label for="nik">NIK:</label>
      {{form.nik}}
      <label for="jumlahvaksin">Pendaftaran Vaksin Ke-:</label>
      {{form.jumlahvaksin}}
      <label for="tanggalvaksin">Tanggal Vaksinasi:</label>
      {{form.tanggalvaksin}}
      <label for="lokasivaksin">Lokasi Vaksinasi:</label>
      {{form.lokasivaksin}}
      

    </fieldset>
  </button>
  <button type="submit">Submit</button>
  <button class="btn btn-outline-secondary" id="punyaadmin">
  <a href="/form">List Peserta Vaksin</a>
  </button>
</form>
{% include "main/footer.html" %}
  
{% endblock content %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
{% if not user.is_superuser %}
<script src="{% static 'js/hide.js' %}"></script>
{% endif %}
{% endblock js %}

form_vaksin/templates/vaksin_index.html
<!DOCTYPE html>
<html lang="en">
  {% block meta %}
    <meta charset="UTF-8" />
    <title>Data Vaksin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  {% endblock meta %}
  
{% block content %}
    {% include "main/header.html" %}
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">DOB</th>
          <th scope="col">NIK</th>
          <th scope="col">Vaksin Ke-</th>
          <th scope="col">Tanggal Vaksin</th>
          <th scope="col">Lokasi Vaksin</th>
        </tr>
      </thead>
      <tbody>
        <!-- TODO loop from Friend model -->
        {% if vaksin %}
          {% for vaksin_ in vaksin %}
        <!-- EXAMPLE SECTION -->
        <tr>
          <td>{{ vaksin_.name }}</td>
          <td>{{ vaksin_.dob }}</td>
          <td>{{ vaksin_.nik }}</td>
          <td>{{ vaksin_.jumlahvaksin }}</td>
          <td>{{ vaksin_.tanggalvaksin }}</td>
          <td>{{ vaksin_.lokasivaksin }}</td>
        </tr>
          {% endfor %}
        {% endif %}
    <!-- END SECTION -->
      </tbody>
    
    </table>
    {% include "main/footer.html" %}
    {% endblock content %}
</html>

main/templates/form_vaksin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'form_vaksin.css' %}">
    <title>Pendaftaran Vaksinasi</title>
</head>
<body>
    <h1>Form Pendaftaran Vaksinasi</h1>
    <!-- <div>class="form"</div> -->
    <form action="" method="POST">
		{% csrf_token %}
        <fieldset>
            <legend><span class="number">1</span>Message Info</legend>
            <label for="name">Nama:</label>
            {{form.name}}
            <label for="DOB">DOB:</label>
            {{form.DOB}}
            <label for="NIK">NIK:</label>
            {{form.noKTP}}
        </fieldset>
          
          <button type="submit">Submit</button>
        </form>    
    </form>
    
    
</body>
</html>

main/templates/main/footer.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/footer.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap" rel="stylesheet">
    </head>

    <body>
        <footer>
            <ul class="anggota">
                <li><a href="#">Alaida</a></li>
                <li><a href="#">Arin</a></li>
                <li><a href="#">Dzikri</a></li>
                <li><a href="#">Ezra</a></li>
                <li><a href="#">Fadhil</a></li>
                <li><a href="#">Joya</a></li>
                <li><a href="#">Luthfi</a></li>
            </ul>
        </footer>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    </body>

</html>

main/templates/main/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/header.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>

    <body>
<div class="topnav" id="myTopnav">
  <label class="logo" >TK F09</label>
  <a href="/login" class="active" ><span id="login-button">Login</span></a>
  <a href="/sertifikat_vaksin">Sertifikat Vaksin</a>
  <a href="/form/add">Daftar Vaksin</a>
  <a href="/form-postingan/">Tambah Postingan</a>
  <a href="/information">Informasi</a>
  <a href="/">Beranda</a>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>
<script>
function myFunction() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}
</script>
    </body>

</html>

main/templates/main/newspage.html
{% extends 'newspagebase.html' %}
{% load static %}

{% block content %}
	{% for object in newspage %}
		<h1>{{ object.Title }}</h1>
		<h2>{{ object.Post }}</h2>
	{% endfor %}
{% endblock %}

main/templates/main/result.html
  <meta charset="UTF-8" />
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style> 


  body {
    position:absolute;
    display: flex;
    flex-direction: column;
    width: 100%;

  }

  hr{
    border-top: 5px solid rgb(92, 27, 27);
  }

  .text{
    color:rgb(94, 93, 93);
    overflow:hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    font-size:large;
  }

  .card{
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  }
  .card:hover {
      box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }

  </style>
  {% extends 'base.html' %}
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <title>Hasil Search</title>
  </head>

  {% block content %}
  {% include "main/header.html" %}

  <body>
    <div style="z-index:1;width:100%;height:auto;min-height: 600px;overflow-y:auto;padding:50px;padding-left: 100px;padding-right: 100px;position:relative">
    {% if results %}
    <div style="align-items: left;">
    <h1>Hasil Pencarian</h1><br>
        {% for result in results %}
          <div class="card" style="width:inherit;height: auto">
            <div class="card-body">
              <h2 class="card-title" style="padding:10px"><b>{{ result.Title }}</b></h2>
              <img src="{{ result.File }}" alt="{{result.Title}}" width="100%" height="auto">
                <div class="card-text">
                  <p class="text" style="padding:10px">{{ result.Post }}</p>
                </div>
            </div>
          </div>
          <br>
        {% endfor %}
    </div>
    {% else %}
        <div style="align-items: center;display: flex;flex-direction: column;">
          <h1><b>Hasil Pencarian tidak ditemukan</b></h1>
          <p>Coba cari dengan kata kunci yang lain</p>
        </div>
    {% endif %}
    </div>
    <!-- <div class="waves" style="position:fixed"></div> -->
    <p id="thing"></p>
  </body>
<script>
  $(document).ready(function(){$.ajax({
    url: "{% url 'main:time_json' %}",
    dataType: "json",
    success:function(result){
      console.log(result)
      document.getElementById("thing").innerHTML = "Menunjukkan data yang ada sebelum " + result;
    }
  })
  })
</script>
    {% include "main/footer.html" %}
    {% endblock content %}

main/templates/main/tempSearch.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{{ title }}</title>
    <meta charset="UTF-8"/>
  </head>
  <body>
  <div style="padding:50px;text-align: center">
    <form action="{% url 'main:result' %}" method = get style="padding:10px">
        <h3>Cari Postingan Menarik mengenai Covid-19</h3>
        <input type=text name="search"/>
        <button type="submit">Search</button>
    </form>
  </div>
  </body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>
{% block js %}

{% endblock js %}

</html>

templates/information.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% include "main/header.html" %}
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/newspagebase.html
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	{% block content %}
	{% endblock content%}
</body>
</html>